# Generated by Django 3.1b1 on 2020-07-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0002_auto_20200706_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='telegram_users',
        ),
    ]
