# Generated by Django 3.1b1 on 2020-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0003_auto_20200706_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.TextField(default=1, verbose_name='Is Banned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.TextField(default=23, verbose_name='subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='Telegram_id'),
        ),
    ]
