# Generated by Django 3.1b1 on 2020-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0004_auto_20200706_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban',
            field=models.TextField(default=False, verbose_name='Is Banned'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='subscription'),
        ),
    ]
