# Generated by Django 3.1b1 on 2020-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0005_auto_20200706_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Is Banned'),
        ),
    ]
