# Generated by Django 2.2 on 2020-08-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0006_auto_20200706_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
