# Generated by Django 2.2 on 2020-08-04 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0007_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.TextField(blank=True, default='', verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default=0, max_length=250, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='unban',
            field=models.BooleanField(default=True, verbose_name='Is UnBanned'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(default=0, max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
