# Generated by Django 2.2 on 2020-08-04 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0008_auto_20200804_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date_two',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description_two',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname_two',
            field=models.TextField(blank=True, default='', verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='link_two',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='price_two',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='user',
            name='title_two',
            field=models.CharField(default=0, max_length=250, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_date_two',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url_two',
            field=models.SlugField(default=0, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
