# Generated by Django 2.2 on 2020-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0009_auto_20200804_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Telegram_id'),
        ),
    ]
