# Generated by Django 2.2 on 2020-08-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0010_auto_20200805_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
