# Generated by Django 2.2 on 2020-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0014_auto_20201001_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_date5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_date5',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar10',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar2',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar3',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar4',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar5',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar6',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar7',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar8',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar9',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name1',
            field=models.TextField(blank=True, default='', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name2',
            field=models.TextField(blank=True, default='', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name3',
            field=models.TextField(blank=True, default='', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name4',
            field=models.TextField(blank=True, default='', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title1',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title2',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title3',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title4',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
    ]
