# Generated by Django 2.2 on 2020-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0015_auto_20201001_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar1',
            field=models.TextField(blank=True, default='', verbose_name='Код интимки'),
        ),
    ]
