# Generated by Django 2.2 on 2020-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0016_user_avatar1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar11',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar12',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar13',
            field=models.TextField(blank=True, default='', verbose_name='Код интимки'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar14',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar10',
            field=models.TextField(blank=True, default='', verbose_name='Код интимки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar4',
            field=models.TextField(blank=True, default='', verbose_name='Код интимки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar5',
            field=models.TextField(blank=True, default='', verbose_name='Код обнаж.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar6',
            field=models.TextField(blank=True, default='', verbose_name='Код превью'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar7',
            field=models.TextField(blank=True, default='', verbose_name='Код интимки'),
        ),
    ]
