# Generated by Django 2.2 on 2020-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0018_auto_20201026_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prime',
            field=models.BooleanField(default=False, verbose_name='PRIME'),
        ),
    ]
