# Generated by Django 2.2 on 2020-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0021_auto_20201028_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
